---
- name: Webserver Compute Configuration
  hosts: tag_Ansible_webserver
  become: yes
  user: ec2-user
  vars:
    ansible_ssh_private_key_file: ~/.ssh/ansible-key.pem
    gitrepo: https://github.com/jesperberth/tomato-monkey.git
  tasks:
  - name: Wait for connection
    git:
      repo: "{{ gitrepo }}"
      dest: "/var/www/html"