---
- name: AWS Webserver Infrastructure
  hosts: localhost
  vars:
    vpc_name: "webserver-vpc"
    project_name: "ansible"
    region: "eu-west-1"
    cidr: "10.0.0.0/16"
    cidr_public_a: "10.0.1.0/24"
    cidr_public_b: "10.0.4.0/24"
    zone1: "a"
    zone2: "b"
  
  tasks:
  - name: create ELB
    ec2_elb_lb:
      state: present
      name: 'New ELB'
      security_group_ids: 'sg-123456, sg-67890'
      region: us-west-2
      subnets: 'subnet-123456,subnet-67890'
      purge_subnets: yes
      listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: 80
  