---
- name: OCI Zone Record
  hosts: localhost
  vars:
    compartmentid: "ocid1.tenancy.oc1..aaaaaaaawkmnjfryshdufax2ar4h4x7ijbnvkcy3kgwun2pcbq7vj6k3xfbq"

  tasks:
  - name: Load Balancer Facts
    oci_load_balancer_facts:
        load_balancer_id: "{{ loadbalancer_id }}"
    register: lb
  
  - name: Set Fact lb_ip fact
    set_fact:
      lb_public_ip: "{{ item.ip_addresses }}"
    loop: "{{ lb.load_balancers }}"

  - name: Set Fact loadbalancer_ip fact
    set_fact:
      loadbalancer_public_ip: "{{ item.ip_address }}"
    loop: "{{ lb_public_ip }}"

  - name: Add zone record for loadbalancer
    oci_zone_records:
      name: "{{ tld }}"
      patch_items: [{
                      domain: "{{ hostname }}.{{ tld }}",
                      is_protected: false,
                      rdata: "{{ loadbalancer_public_ip }}",
                      rtype: "A",
                      ttl: 3600,
                      operation: "ADD"
                      }]