---
- name: OCI Webserver Loadbalancer
  hosts: localhost
  vars:
    compartmentid: "ocid1.tenancy.oc1..aaaaaaaawkmnjfryshdufax2ar4h4x7ijbnvkcy3kgwun2pcbq7vj6k3xfbq"

  tasks:
  - name: Get details of Webserver1
    oci_instance_facts:
      compartment_id: "{{ compartmentid }}"
      lifecycle_state: "RUNNING"
      display_name: "webserver1"
    register: webserver1
  - debug:
      msg: "{{ webserver1 }}"
  - set_fact:
      webserver1_pub_ip: "{{ webserver1.instance.primary_public_ip }}"
  
  - name: Get details of Webserver2
    oci_instance_facts:
      compartment_id: "{{ compartmentid }}"
      lifecycle_state: "RUNNING"
      display_name: "webserver2"
    register: webserver2
  - debug:
      msg: "{{ webserver2 }}"
  - set_fact:
      webserver2_pub_ip: "{{ webserver2.instance.primary_public_ip }}"