---
- name: OCI Webserver Loadbalancer
  hosts: localhost
  vars:
    compartmentid: "ocid1.tenancy.oc1..aaaaaaaawkmnjfryshdufax2ar4h4x7ijbnvkcy3kgwun2pcbq7vj6k3xfbq"

  tasks:
  - name: Get details of Webserver1
    oci_instance_facts:
      #compartment_id: "{{ compartmentid }}"
      instance_id: "ocid1.instance.oc1.eu-frankfurt-1.antheljsjq645facxw6ahfxolgxhsf6ckeoeetqnwcy4a4f4vlba26kvt7kq"
    register: webserver1
  - debug:
      msg: "{{ webserver1 }}"
  - set_fact:
      webserver1_pub_ip: "{{ webserver1.instances.primary_public_ip }}"
  - debug:
    msg: "{{ webserver1_pub_ip }}"
  
