---
- name: OCI Webserver Loadbalancer
  hosts: localhost
  vars:
    compartmentid: "ocid1.tenancy.oc1..aaaaaaaawkmnjfryshdufax2ar4h4x7ijbnvkcy3kgwun2pcbq7vj6k3xfbq"

  tasks:
  - name: Get details of Instances
    oci_instance_facts:
      compartment_id: "{{ compartmentid }}"
      lifecycle_state: "running"
    register: instances
  - debug:
      msg: "{{ instances }}"
#  - set_fact:
#      webserver1_id: "{{ webserver1.instance.id }}"